server.port: 8080
server.servlet.context-path: /chen  
jdbc.driver: com.mysql.jdbc.Driver
jdbc.url: jdbc:mysql://localhost:3306/sbm?useUnicode=true&characterEncoding=utf-8&useSSL=false
jdbc.username: root
jdbc.password: root123

testValue: 你猜猜看我的配置值

person: 
   name: zhangsan 
   age: 45